### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by xbubbo** [InterstellarNetwork/Interstellar#603]
# TO DO
- [ ] Bare Server Switcher
- [ ] Volume Customizer on Tabs Page
- [ ] More Themes & Fix Custom Themes
- [ ] Mobile Support (CSS)
- [ ] Fix Now.gg Errors

**Comment by IncognitoTGT** [comment]
bare switcher is part of wisp so that can be checked off

**Comment by interstellarforker** [comment]
Anything been pushed?

**Comment by madeline-yana** [comment]
Tab cloak seems to be the only thing that's been pushed so far... Don't quote me on that, though.

**Comment by madeline-yana** [comment]
ah

**Comment by madeline-yana** [comment]
If it is even on the radar, CloudFlare protection *is* broken

**Comment by reherio** [comment]
pls fix snapchat

**Comment by IncognitoTGT** [comment]
can't be fixed

**Comment by reherio** [comment]
oh

**Comment by madeline-yana** [comment]
Would help to state why/how it's broken...

**Comment by WatchGamingVideos** [comment]
excited for tools page

**Comment by RisingGlitch** [comment]
" Allow users to manually make themes. " has already been done

**Comment by IncognitoTGT** [comment]
just checked that

**Comment by Yashneel123** [comment]
what about roblox im not addicted, is roblox fixed?

**Comment by IncognitoTGT** [comment]
It's not, check #552 for updates
